import type { Module, Recipe } from "./types"

export const modules: Module[] = [
  {
    id: "coach-launch",
    title: "Coach Launch Playbook",
    description: "Essential resources to kickstart your coaching journey and build a strong foundation.",
    category: "Getting Started",
    order: 1,
    forNewCoach: true,
    icon: "🚀",
    resources: [
      {
        id: "launch-1",
        title: "Getting Started as a New Coach",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "launch-2",
        title: "First 30 Days Action Plan",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "launch-3",
        title: "Coach Launch Video Training",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
  {
    id: "client-month-one",
    title: "Launching a Client & Month One",
    description: "Step-by-step guidance for supporting clients through their critical first month.",
    category: "Client Support",
    order: 2,
    forNewCoach: true,
    icon: "🎯",
    resources: [
      {
        id: "client-1",
        title: "Client Onboarding Checklist",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "client-2",
        title: "First Month Coaching Framework",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "client-3",
        title: "Setting Client Expectations",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
  {
    id: "client-support",
    title: "Client Support Texts & Videos",
    description: "Ready-to-use communication templates and video resources for effective client support.",
    category: "Client Support",
    order: 3,
    forNewCoach: true,
    icon: "💬",
    resources: [
      {
        id: "support-1",
        title: "Weekly Check-in Text Templates",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "support-2",
        title: "Motivational Message Library",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "support-3",
        title: "Client Support Video Series",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
  {
    id: "branding",
    title: "Branding Your Business",
    description: "Tools and strategies to create a compelling personal brand that attracts clients.",
    category: "Business Building",
    order: 4,
    forNewCoach: true,
    icon: "✨",
    resources: [
      {
        id: "brand-1",
        title: "Personal Branding Toolkit",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "brand-2",
        title: "Branding Quick Links & Resources",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "brand-3",
        title: "Creating Your Brand Story",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
  {
    id: "social-media",
    title: "Social Media Strategy",
    description: "Proven social media tactics to grow your audience and generate leads.",
    category: "Business Building",
    order: 5,
    forNewCoach: false,
    icon: "📱",
    resources: [
      {
        id: "social-1",
        title: "Social Media Content Calendar",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "social-2",
        title: "Platform-Specific Strategies",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "social-3",
        title: "Social Media Growth Training",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
  {
    id: "gold-standard",
    title: "Gold Standard Trainings",
    description: "Advanced coaching techniques and best practices for experienced coaches.",
    category: "Training",
    order: 6,
    forNewCoach: false,
    icon: "🏆",
    resources: [
      {
        id: "gold-1",
        title: "Gold Standard Coaching Framework",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "gold-2",
        title: "Advanced Client Strategies",
        type: "doc",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "gold-3",
        title: "Gold Standard Video Trainings",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
      {
        id: "gold-4",
        title: "Mastering Client Transformations",
        type: "video",
        url: "https://docs.google.com/document/d/1QT3Z2vKcfPBs-HvPQkpciHKkmLkOxXnqcuA-UifgFKI/edit",
      },
    ],
  },
]

export const recipes: Recipe[] = [
  {
    id: "recipe-1",
    title: "Grilled Lemon Herb Chicken",
    description: "Juicy grilled chicken breast marinated in fresh lemon and herbs, served with steamed broccoli.",
    image: "/grilled-lemon-herb-chicken-with-broccoli.jpg",
    category: "Chicken",
    prepTime: 15,
    cookTime: 20,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz boneless, skinless chicken breast",
      "2 cups broccoli florets",
      "2 tbsp fresh lemon juice",
      "1 tsp dried oregano",
      "1 tsp garlic powder",
      "Salt and pepper to taste",
      "Cooking spray",
    ],
    instructions: [
      "Combine lemon juice, oregano, garlic powder, salt, and pepper in a bowl.",
      "Add chicken and marinate for at least 10 minutes.",
      "Preheat grill or grill pan to medium-high heat.",
      "Grill chicken for 6-8 minutes per side until fully cooked (internal temp 165°F).",
      "Steam broccoli until tender, about 5-7 minutes.",
      "Serve chicken with broccoli and enjoy!",
    ],
  },
  {
    id: "recipe-2",
    title: "Pan-Seared Salmon with Asparagus",
    description: "Perfectly seared salmon fillet with crispy skin, paired with roasted asparagus.",
    image: "/pan-seared-salmon-with-asparagus.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 1, condiment: 0 },
    ingredients: [
      "5-7 oz salmon fillet",
      "2 cups asparagus spears",
      "1 tsp olive oil",
      "1 tsp lemon zest",
      "Fresh dill",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Pat salmon dry and season with salt, pepper, and lemon zest.",
      "Heat olive oil in a non-stick pan over medium-high heat.",
      "Place salmon skin-side down and cook for 5-6 minutes without moving.",
      "Flip and cook for another 3-4 minutes until desired doneness.",
      "Roast asparagus at 400°F for 10-12 minutes.",
      "Garnish salmon with fresh dill and serve with asparagus.",
    ],
  },
  {
    id: "recipe-3",
    title: "Beef Stir-Fry with Bell Peppers",
    description: "Tender beef strips stir-fried with colorful bell peppers in a light sauce.",
    image: "/beef-stir-fry-with-bell-peppers.jpg",
    category: "Beef",
    prepTime: 15,
    cookTime: 12,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz lean beef strips",
      "1.5 cups sliced bell peppers (red, yellow, green)",
      "1 cup snap peas",
      "2 tbsp low-sodium soy sauce",
      "1 tsp ginger, minced",
      "2 cloves garlic, minced",
      "Cooking spray",
    ],
    instructions: [
      "Season beef strips with salt and pepper.",
      "Heat a wok or large skillet over high heat and spray with cooking spray.",
      "Stir-fry beef for 3-4 minutes until browned, then remove.",
      "Add peppers and snap peas, stir-fry for 3-4 minutes.",
      "Return beef to pan, add soy sauce, ginger, and garlic.",
      "Toss everything together for 2 minutes and serve hot.",
    ],
  },
  {
    id: "recipe-4",
    title: "Turkey Lettuce Wraps",
    description: "Flavorful ground turkey wrapped in crisp lettuce leaves with Asian-inspired seasonings.",
    image: "/turkey-lettuce-wraps.jpg",
    category: "Turkey",
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz lean ground turkey",
      "6-8 large lettuce leaves",
      "1 cup diced cucumber",
      "1/2 cup shredded carrots",
      "2 tbsp rice vinegar",
      "1 tsp sesame seeds",
      "Green onions, chopped",
    ],
    instructions: [
      "Cook ground turkey in a skillet over medium heat until browned.",
      "Season with garlic powder, ginger, and a splash of rice vinegar.",
      "Prepare lettuce leaves by washing and patting dry.",
      "Mix cucumber and carrots in a bowl.",
      "Spoon turkey into lettuce leaves.",
      "Top with veggie mixture, sesame seeds, and green onions.",
    ],
  },
  {
    id: "recipe-5",
    title: "Herb-Crusted Pork Tenderloin",
    description: "Tender pork tenderloin with a flavorful herb crust, served with roasted Brussels sprouts.",
    image: "/herb-crusted-pork-tenderloin-brussels-sprouts.jpg",
    category: "Pork",
    prepTime: 15,
    cookTime: 25,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz pork tenderloin",
      "2 cups Brussels sprouts, halved",
      "2 tsp Dijon mustard",
      "1 tsp dried rosemary",
      "1 tsp dried thyme",
      "Salt and pepper",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Rub pork with Dijon mustard, then coat with herbs, salt, and pepper.",
      "Sear pork in an oven-safe skillet for 2 minutes per side.",
      "Transfer skillet to oven and roast for 15-20 minutes.",
      "Toss Brussels sprouts with cooking spray and roast for 20 minutes.",
      "Let pork rest 5 minutes before slicing and serve with Brussels sprouts.",
    ],
  },
  {
    id: "recipe-6",
    title: "Vegetarian Cauliflower Steak",
    description: "Thick-cut cauliflower steaks roasted with herbs and spices, served with a mixed green salad.",
    image: "/roasted-cauliflower-steak-with-salad.jpg",
    category: "Vegetarian",
    prepTime: 10,
    cookTime: 25,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 0, green: 3, fat: 1, condiment: 1 },
    ingredients: [
      "1 large cauliflower head, cut into steaks",
      "2 cups mixed greens",
      "1 cup cherry tomatoes, halved",
      "1 tsp olive oil",
      "1 tsp smoked paprika",
      "1 tsp cumin",
      "Balsamic vinegar",
    ],
    instructions: [
      "Preheat oven to 425°F.",
      "Brush cauliflower steaks with olive oil.",
      "Season with paprika, cumin, salt, and pepper.",
      "Roast for 20-25 minutes, flipping halfway through.",
      "Toss greens and tomatoes with balsamic vinegar.",
      "Serve cauliflower steak over salad.",
    ],
  },
  {
    id: "recipe-7",
    title: "Breakfast Egg White Scramble",
    description: "Fluffy egg white scramble packed with colorful vegetables for a protein-rich start.",
    image: "/egg-white-scramble-with-vegetables.jpg",
    category: "Breakfast",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 0 },
    ingredients: [
      "1 cup egg whites (or 4-5 egg whites)",
      "1 cup spinach",
      "1/2 cup diced tomatoes",
      "1/2 cup mushrooms, sliced",
      "Salt and pepper",
      "Cooking spray",
    ],
    instructions: [
      "Heat a non-stick pan over medium heat with cooking spray.",
      "Add mushrooms and cook for 2-3 minutes.",
      "Add spinach and tomatoes, cook until spinach wilts.",
      "Pour in egg whites and season with salt and pepper.",
      "Scramble gently until eggs are fully cooked.",
      "Serve immediately.",
    ],
  },
  {
    id: "recipe-8",
    title: "Garlic Shrimp with Zucchini Noodles",
    description: "Succulent garlic shrimp served over fresh zucchini noodles for a light, satisfying meal.",
    image: "/garlic-shrimp-with-zucchini-noodles.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 8,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz shrimp, peeled and deveined",
      "2 medium zucchini, spiralized",
      "3 cloves garlic, minced",
      "1 tbsp lemon juice",
      "Red pepper flakes",
      "Fresh parsley",
      "Cooking spray",
    ],
    instructions: [
      "Heat a large skillet over medium-high heat with cooking spray.",
      "Add shrimp and cook for 2 minutes per side until pink.",
      "Remove shrimp and set aside.",
      "Add garlic to pan and cook for 30 seconds.",
      "Add zucchini noodles and cook for 2-3 minutes.",
      "Return shrimp to pan, add lemon juice, and toss. Garnish with parsley.",
    ],
  },
  {
    id: "recipe-9",
    title: "Chicken Fajita Bowl",
    description: "Seasoned chicken strips with sautéed peppers and onions over fresh greens.",
    image: "/chicken-fajita-bowl-with-peppers.jpg",
    category: "Chicken",
    prepTime: 15,
    cookTime: 15,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz chicken breast, sliced",
      "1 cup bell peppers, sliced",
      "1 cup onions, sliced",
      "1 cup romaine lettuce",
      "2 tsp fajita seasoning",
      "Lime wedges",
      "Cooking spray",
    ],
    instructions: [
      "Season chicken with fajita seasoning.",
      "Heat skillet over medium-high heat with cooking spray.",
      "Cook chicken for 5-6 minutes until fully cooked, then remove.",
      "Add peppers and onions to pan, cook for 5 minutes.",
      "Arrange lettuce in a bowl.",
      "Top with chicken and vegetables, serve with lime wedges.",
    ],
  },
  {
    id: "recipe-10",
    title: "Mediterranean Cod",
    description: "Flaky cod fillet baked with tomatoes, olives, and Mediterranean herbs.",
    image: "/mediterranean-baked-cod-with-tomatoes.jpg",
    category: "Seafood",
    prepTime: 10,
    cookTime: 20,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz cod fillet",
      "1 cup cherry tomatoes",
      "1 cup green beans",
      "5 Kalamata olives, sliced",
      "1 tsp dried oregano",
      "Lemon juice",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 400°F.",
      "Place cod in a baking dish sprayed with cooking spray.",
      "Top with tomatoes, olives, and oregano.",
      "Bake for 15-18 minutes until fish flakes easily.",
      "Steam green beans until tender.",
      "Drizzle fish with lemon juice and serve with green beans.",
    ],
  },
  {
    id: "recipe-11",
    title: "Turkey Meatballs with Marinara",
    description: "Lean turkey meatballs simmered in sugar-free marinara sauce with side salad.",
    image: "/turkey-meatballs-with-marinara-sauce.jpg",
    category: "Turkey",
    prepTime: 15,
    cookTime: 25,
    servings: 1,
    difficulty: "Medium",
    counts: { lean: 1, green: 3, fat: 0, condiment: 2 },
    ingredients: [
      "5-7 oz ground turkey",
      "1 egg white",
      "2 cups marinara sauce (sugar-free)",
      "2 cups mixed greens",
      "1 tsp Italian seasoning",
      "Garlic powder",
      "Cooking spray",
    ],
    instructions: [
      "Preheat oven to 375°F.",
      "Mix turkey, egg white, Italian seasoning, and garlic powder.",
      "Form into 6-8 meatballs and place on baking sheet.",
      "Bake for 20 minutes until cooked through.",
      "Heat marinara sauce in a pan.",
      "Add meatballs to sauce and simmer for 5 minutes. Serve with salad.",
    ],
  },
  {
    id: "recipe-12",
    title: "Spicy Beef Lettuce Cups",
    description: "Spicy seasoned ground beef served in crisp lettuce cups with fresh toppings.",
    image: "/spicy-beef-lettuce-cups.jpg",
    category: "Beef",
    prepTime: 10,
    cookTime: 12,
    servings: 1,
    difficulty: "Easy",
    counts: { lean: 1, green: 3, fat: 0, condiment: 1 },
    ingredients: [
      "5-7 oz lean ground beef",
      "6-8 butter lettuce leaves",
      "1 cup diced tomatoes",
      "1/2 cup diced cucumbers",
      "Chili powder",
      "Cumin",
      "Lime juice",
    ],
    instructions: [
      "Brown ground beef in a skillet over medium heat.",
      "Season with chili powder, cumin, salt, and pepper.",
      "Drain any excess fat.",
      "Prepare lettuce cups and arrange on a plate.",
      "Fill each cup with seasoned beef.",
      "Top with tomatoes and cucumbers, squeeze lime juice over.",
    ],
  },
]
